import { StatusProducao } from './status-producao';
import { Tags } from './tags';
import { Categoria } from './categoria';
import { SubCategoria } from './subcategoria';
import { Editora } from './editora';
import { MembroEquipeTecnica } from './membro-equipe-tecnica';
export class LivroDigital {
    id: number;
    isbnDigital: string;
    titulo: string;
    subTitulo: string;
    edicao: number;
    ano: number;
    autoria: string;
    idTipoLivro?: number;
    paginas: number;
    idEditora: number;
    idIdioma: number;
    colecaoSerie: string;
    volume: number;
    idPais: number;
    sinopse: string;
    idCategoria: number;
    idSubCategoria: number;
    // capa: any;
    capaString: string;
    complemento: string;
    observacoes: string;
    isbnImpresso?: string;
    codAxLivroImpresso?: string;
    codAxLivroDigital?: string;
    cod5Elemento?: string;
    precoDigital?: number;
    precoImpresso?: number;
    linkLivroDigital?: string;
    linkLivroImpresso?: string;
    texto4Capa?: string;
    sumario?: string;
    sumarioReduzido?: string;
    dtaCadastro?: Date;
    skuECommerce?: string;
    tags: Array<Tags>;

    categoria: Categoria;
    subCategoria: SubCategoria;
    editora: Editora;
    statusProducao: StatusProducao;
    membroEquipeTecnica: Array<MembroEquipeTecnica>;
}